url: "https://jiahuikchen.github.io/"
baseurl: ""
title: "Jiahui (Karen) Chen's Website"
description: "Software engineer at Facebook, computer scientist and researcher interested in AI/ML."
avatar: "/img/grad_close.PNG"
avatarurl: "https://jiahuikchen.github.io/about-me/"

navbar-links:
#   Papers:
#     - Google Scholar: "https://scholar.google.com/citations?user=73kzHn4AAAAJ&hl=en"
  Portfolio:
    - LinkedIn: "https://linkedin.com/in/jiahui-k-chen/"
    - Resume & CV: "resume"
    - Papers (Google Sholar): "https://scholar.google.com/citations?user=73kzHn4AAAAJ&hl=en"
    - Code (GitHub): "https://github.com/JiahuiKChen"
    # - Instagram: "https://www.instagram.com/jiahui.k.chen"

  # Resume/CV: "resume"

  Blog: "https://jiahui-k-chen.medium.com/"

  About Me: "about-me"

author:
  name: "Jiahui (Karen) Chen"
  email: "jiahui.k.chen@gmail.com"
  github: "JiahuiKChen"
  instagram: "jiahui.k.chen"
  googlescholar: "73kzHn4AAAAJ&hl=en"
  linkedin: "in/jiahui-k-chen/"

footer-links-active:
  email: true
  instagram: true
  github: true
  googlescholar: true
  impactstory: false
  linkedin: true
  twitter: false
  facebook: false
  rss: false
  stackoverflow: false

# url-pretty: "jiahuikchen.me"

timezone: "America/Los_Angeles"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 30

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
